from typing import Any

class BaseCallback:
    def on_module_start(self, call_id: str, instance: Any, inputs: dict[str, Any]) -> None: ...
    def on_module_end(self, call_id: str, outputs: Any | None, exception: Exception | None = None) -> None: ...
    def on_lm_start(self, call_id: str, instance: Any, inputs: dict[str, Any]) -> None: ...
    def on_lm_end(self, call_id: str, outputs: dict[str, Any] | None, exception: Exception | None = None) -> None: ...
    def on_tool_start(self, call_id: str, instance: Any, inputs: dict[str, Any]) -> None: ...
    def on_tool_end(self, call_id: str, outputs: dict[str, Any] | None, exception: Exception | None = None) -> None: ...
