"""Minimal type stub for the ``unidecode`` package."""

def unidecode(string: str, errors: str = ..., replace_str: str = ...) -> str: ...
def unidecode_expect_ascii(string: str, errors: str = ..., replace_str: str = ...) -> str: ...
def unidecode_expect_nonascii(string: str, errors: str = ..., replace_str: str = ...) -> str: ...

__all__ = ["unidecode", "unidecode_expect_ascii", "unidecode_expect_nonascii"]
